### PR TITLE
Refactor Bluetooth logic into a RedBearDuo class

### PR DESCRIPTION
**Pull request by dziemborowicz**
This change removes the RBLService and the supporting RBLGattAttributes class, and replaces them with a RedBearDuo class that has a simpler interface.

The new implementation uses features that require minSdkVersion 21 and Java 8, so the app build.gradle file is updated accordingly.

### CODE REVIEW

**Comment by dziemborowicz** [comment]
I've removed the references to RedBear Duo, renaming RedBearDuo to BLEDevice and RedBearDuoUtil to BLEUtil. There are better names.

The code is still tightly coupled with the .ino implementation because it relies on the specific characteristics that are set up on the device to emulate a data channel. But none of that is specific to the RedBear Duo board. It works with anything, so long as the right characteristics are set up on it in the right way.

For the listener, you can refer to nested listeners with syntax like BLEDevice.Listener, which has similar readability to something like BLEDeviceListener. But it doesn't really matter to me one way or the other, so I promoted the listener interface to the top level as BLEListener.

**Comment by jonfroehlich** [comment]
Thanks Chris. Makes sense. Really thankful for your continued work here and explaining your design rationale a bit more. I hope to have time to review this in the morning and will likely then merge.

@EdigaHe, can we credit Chris with +1 bonus points (5% of total assignment) for his work on this please?

**Comment by EdigaHe** [comment]
Yes, I will credit Chirs with +1 bonus points for his effort. Thanks Chris.

**Comment by dziemborowicz** [comment]
Thanks! :)

**Pull request merged**
